// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/Envelope.proto

package worker_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务处理请求
type TaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务ID
	TaskId string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	// 任务信息(JSON)
	Task string `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	// 任务创建时间
	Timestamp     uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_Envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_Envelope_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *TaskRequest) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 任务处理响应
type TaskReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 任务ID
	TaskId string `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	// 是否成功
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 任务结果（JSON）
	Solution string `protobuf:"bytes,3,opt,name=solution,proto3" json:"solution,omitempty"`
	// 错误码
	ErrorCode string `protobuf:"bytes,4,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 错误消息（如果有最好）
	ErrorMsg      string `protobuf:"bytes,5,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskReply) Reset() {
	*x = TaskReply{}
	mi := &file_proto_Envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskReply) ProtoMessage() {}

func (x *TaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskReply.ProtoReflect.Descriptor instead.
func (*TaskReply) Descriptor() ([]byte, []int) {
	return file_proto_Envelope_proto_rawDescGZIP(), []int{1}
}

func (x *TaskReply) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskReply) GetSolution() string {
	if x != nil {
		return x.Solution
	}
	return ""
}

func (x *TaskReply) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TaskReply) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_proto_Envelope_proto protoreflect.FileDescriptor

const file_proto_Envelope_proto_rawDesc = "" +
	"\n" +
	"\x14proto/Envelope.proto\x12\vworker_grpc\"W\n" +
	"\vTaskRequest\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"\x93\x01\n" +
	"\tTaskReply\x12\x16\n" +
	"\x06taskId\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1a\n" +
	"\bsolution\x18\x03 \x01(\tR\bsolution\x12\x1c\n" +
	"\terrorCode\x18\x04 \x01(\tR\terrorCode\x12\x1a\n" +
	"\berrorMsg\x18\x05 \x01(\tR\berrorMsg2K\n" +
	"\rWorkerService\x12:\n" +
	"\x04Work\x12\x18.worker_grpc.TaskRequest\x1a\x16.worker_grpc.TaskReply\"\x00B>\n" +
	"\x1bcom.zero.grpc.iface.messageB\x0fEnvelopeMessageZ\x0e./;worker_grpcb\x06proto3"

var (
	file_proto_Envelope_proto_rawDescOnce sync.Once
	file_proto_Envelope_proto_rawDescData []byte
)

func file_proto_Envelope_proto_rawDescGZIP() []byte {
	file_proto_Envelope_proto_rawDescOnce.Do(func() {
		file_proto_Envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_Envelope_proto_rawDesc), len(file_proto_Envelope_proto_rawDesc)))
	})
	return file_proto_Envelope_proto_rawDescData
}

var file_proto_Envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_Envelope_proto_goTypes = []any{
	(*TaskRequest)(nil), // 0: worker_grpc.TaskRequest
	(*TaskReply)(nil),   // 1: worker_grpc.TaskReply
}
var file_proto_Envelope_proto_depIdxs = []int32{
	0, // 0: worker_grpc.WorkerService.Work:input_type -> worker_grpc.TaskRequest
	1, // 1: worker_grpc.WorkerService.Work:output_type -> worker_grpc.TaskReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Envelope_proto_init() }
func file_proto_Envelope_proto_init() {
	if File_proto_Envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_Envelope_proto_rawDesc), len(file_proto_Envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Envelope_proto_goTypes,
		DependencyIndexes: file_proto_Envelope_proto_depIdxs,
		MessageInfos:      file_proto_Envelope_proto_msgTypes,
	}.Build()
	File_proto_Envelope_proto = out.File
	file_proto_Envelope_proto_goTypes = nil
	file_proto_Envelope_proto_depIdxs = nil
}
